### ISSUE TITLE
Sugestão de Projetos para vencermos o roadmap

### ISSUE THREAD

**Issue by julianomour** [training-center/javascript-study-group#10]
Fala pessoal, gostaria de fazer uma sugestão para o grupo de estudos. 
Baseado no roadmap que temos, o que acham de definirmos projetos que sejma divididos por níveis, onde em cada nível seja especificado quais itens do roadmap devem ser usados.
Acho que assim ficaria interessante para os iniciantes se guiarem e não ficarem na dúvida de qual conteúdo estudar primeiro.

Qual a opinião e as sugestões de vocês sobre a ideia ?

**Comment by AlexsandroSA** [comment]
Legal, já pensou em algum projeto? Precisamos pensar em projetos para browser e para nodejs.

**Comment by julianomour** [comment]
Eu comecei um projeto pessoal de criar uma ferramenta de to do list. E incluiria projetos, tarefas, sub tarefas e comentários. Acho que daria pra abranger bem front-end e back-end.
Talvez seja um projeto que pode ser pensado.

**Comment by ruanvalente** [comment]
Gostei, mas como ficaria a divisão do roadmap ? Seria por níveis ?

**Comment by julianomour** [comment]
Seria por níveis sim. Dividiria entre os níveis onde os conteúdos do roadmap deveriam estar pra facilitar o aprendizado e a caminhada pelo roadmap . Sendo assim, ficaria definido o que deve  ser usado no projeto em cada nível.

**Comment by ruanvalente** [comment]
Pow show de bola, você já tem em mente como ficaria essa divisão ? Tipo, ideias para cada projeto pelo seu nível e etc ?

**Comment by julianomour** [comment]
Então galera, eu tbm tô interessado em aprender. Eu dei a ideia pra movimentar o grupo e aprendermos juntos. Precisamos de alguém pra nos ajudar com essa divisão.

**Comment by AlexsandroSA** [comment]
### Esse "alguém" pode ser todo mundo. 

Deixo aqui minha sugestão. Coloque aqui a divisão que você tem em mente e vamos refinando/melhorando ela.

### O que pensei um tempo atrás foi:

Criar projetos que possam ser utilizados em todas as trilhass, por exemplo:

__Iniciante:__
Um blog criado a pessoa tem que fazer as interações em js no blog

__Itermediario__
Deixar o blog mais legal consumindo uma api

__Avançado__
Criar uma api para o blog, com testes, montanto a arquitetura...

Algo nessa linha, não necessariamente um blog mas   um projeto que possamos usar do iniciante ao avançado.

---
Temos uma issue aberta sobre o [a definição do roadmap](https://github.com/training-center/javascript-study-group/issues/7), dá uma olhada lá

**Comment by angelilton** [comment]
acho interessante filtrar primeiro quem está afim e qual é o nível pq ai podemos focar mais tipo quem está no intermediário ajuda o iniciantes e quem está no avançando ajuda o intermediário e por ai vai tipo um Pair Programming

**Comment by AlexsandroSA** [comment]
@angelilton então isso já foi feito - [link](https://github.com/training-center/javascript-study-group/issues/2). 

Além disso precisamos pensar/criar em algo que seja util para outras pessoas que _ainda_ não está no grupo, imagina aquela pessoa que vai entrar daqui a um mês, por exemplo.

Por experiencia própria esse tipo de abordagem, onde um  intermediario ajudar um iniciante, é bem complicado por questões de disponibilidade, e se entrar um novo membro que vai dá suporte? Entende, acabamos gerando uma dependencia que não vamos conseguir sustentar por muito tempo.

Acredito que o melhor a ser feito é projetos onde cada membro faça sózinho (aqui faço uso do conceito que vi no freecodecamp [Read-Search-Ask](https://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514)) e o grupo ajuda a corrigir/revisar.

**Comment by AlexsandroSA** [comment]
Se possível for, mandem sugestões de projetos.

---
[NOME DO PROJETO], [NIVEL] 
Uma breve descrição do projeto...

**Comment by Morette** [comment]
**To-Do List, Nível Intermediário/Avançado**
Acho que esse projeto é bom porque engloba desde HTML,CSS até JS. O nível acho que vai depender da criatividade de cada um, se vai ter mais ou menos recursos.

**Geo-Location, Nível Iniciante/Intermediário**
Um projeto simples. Somete uma caixa para dar um Input e com isso buscar a localização utilizando API do Google Maps.

**Comment by julianomour** [comment]
Acredito que podemos usar o mesmo projeto para níveis diferentes. Aqui vai minha sugestão:

**_To-Do List, Nível Iniciante/Intermediário_**

**- Características**
Um sistema pequeno com adição de projetos e atribuição de tarefas a este projeto. 

**- Itens do Roadmap**

- HTML
- CSS com algum pre processador
- Javascript(ES6).


**_To-Do List, Nível Intermediário/Avançado_**

**- Caracteírsticas**

As mesmas características do anterior, com adição de : 
- Comentários nas tarefas
- Cadastro e login de usuários
- Registro de tudo em algum banco de dados(não sei a opinião de vocês sobre este item)

**- Itens do Roadmap:**

- Além dos itens anteriores, utilizar algum package manager
- Implementar Testes
- Framework(bootstrap, materialize, etc)

Pensei em algo nessa linha...

**Comment by angelilton** [comment]
**jogo estoura balão, Nível Iniciante**

- Características
um gamer que no click estoura o balão e conta quantos estourados com timer regressivo  

- Itens do Roadmap
HTML
CSS 
Javascript.
[arquivo do projeto](https://github.com/angelilton/game-whith-js)

**Comment by crisgon** [comment]
## Jogo da memória -  Intermediário
Criar um jogo da memória com  tempo e pontuação. Um bônus seria ter uma lista de recordes armazenados com localstorage.

## Jogo de palavras - Avançado
Um jogo em que dado uma palavra a pessoa precisa dizer uma palavra que comece com a ultima letra da palavra anterior. Para esse jogo seria necessário o consumo de uma api de dicionário para fazer a verificação da existência da palavra. Também teria tempo e um sistema de pontuação com base no tempo de resposta.

![Imagem do jogo das palavras](https://trello-attachments.s3.amazonaws.com/5a1ef122caef978e8947300a/5a8f61b6875cb6045dfaca3d/3d6ffbdcf6f280c2c593ef0a82cdaa39/image.png)

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by AlexsandroSA** [comment]
Essa acredito que ainda seja relevante mas vou esperar o pessoal se manifestar!!

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?
