### ISSUE TITLE
Resultado da pesquisa sobre reunião do grupo de estudos de JavaScript

### ISSUE THREAD

**Issue by AlexsandroSA** [training-center/javascript-study-group#2]
O resultado apontado pela pesquisa realizada no Google Formulários([link](https://goo.gl/forms/Yh8R6ngCZfZt4en73)) sobre reunião.

Os dados do gráfico foram coletados entre os dias 07 e 10 de Janeiro de 2018, disponivel a todos do grupo __#javascript-studies__ no período informado.

![nivel-de-conhecimento](https://user-images.githubusercontent.com/1703378/34828426-ac91b86e-f6c4-11e7-8f3a-6d06c61e42d9.png)
_Nível de conhecimento em JavaScript_

![ferramenta-para-reuniao](https://user-images.githubusercontent.com/1703378/34828485-d5e0d664-f6c4-11e7-8ba8-e9d30b47dd89.png)
_Ferramenta ideal para reuniões_

![dia-ideal-para-reuniao](https://user-images.githubusercontent.com/1703378/34828513-f7f06fee-f6c4-11e7-92a4-06ab0f863cfc.png)
_Melhores dias para reuniões_

![hora-ideal-para-reuniao](https://user-images.githubusercontent.com/1703378/34828524-01bff1ac-f6c5-11e7-8907-170605de0251.png)
_Melhores horários para reuniões_

**Comment by woliveiras** [comment]
Excelente!

**Comment by AlexsandroSA** [comment]
Com base nos dados apresentados, fica aqui minha sugestão para nossa primeira reunião.

__Ata:__
 - (Re)Apresentação dos membros do grupo
 - Definir plano de estudos
 - Definir metodologias e prazos de troca de conhecimentos(apresentação,code review...) sobre os assuntos estudados

__Onde? Quando? Como?__
- Data: 13/01/2018
- Horário: 20:00
- Duração: 1:30 (maxímo)
- Plataforma: Hangout*

__*__ Vou disponibilizar um link no grupo e um convite para as pessoas que responderam a pesquisa.

Sinta-se a vontade para enviar qualquer sugestão

Grato a todos pela atenção e vamos aos estudos!! ;)

**Comment by annielmenezes** [comment]
Tenho uma dúvida quando ao pessoal que votou: será que realmente eles vão participar da reunião no final de semana? Geral o pessoal se desliga de eventos desse tipo, o horário achei legal, mas não sei se participaria no final de semana apesar de passar, na maioria do tempo, em casa.

**Comment by AlexsandroSA** [comment]
@annielmenezes obrigado pela opnião!

Então man, essa __issue__ foi postada no grupo e pedi a participação de todos, sigo aguardando. :bowtie:

Essa foi minha sugestão mas nada impede que as coisas mudem o ideal é que fique algo bom para a maioria inclusive podemos debater sobre esse ponto na reunião. O que acha?

Nesse primeiro momento queria manter essa data e hora, sei que é complicado mas acho que vale o esforço de 1 hora no sábado.

**Comment by ghost** [comment]
Precisa participar com vídeo ativado? Prq minha webcam tava zuada da ultima vez que testei, mas microfone ta funcionando ok.  :+1:

**Comment by AlexsandroSA** [comment]
@brunogbr não man, o importante é participar.

**Comment by annielmenezes** [comment]
@AlexsandroSA sim, pode ser um tópico para a discussão na primeria reunião. E "sentir" a participação do pessoal

**Comment by AlexsandroSA** [comment]
@annielmenezes sim, concordo com você!

**Comment by AlexsandroSA** [comment]
Pessoal,

Segue o link para ~~[acesso a reunião](#)~~ o mesmo foi compartilhado no slack.

Lembrando que a reunião as 20:00 horário de São Paulo com tempo de tolerância de 10 min.

**Comment by AlexsandroSA** [comment]
Segue a [Pauta](https://github.com/training-center/javascript-study-group/blob/master/material/agenda/README.md#1º-reunião) e a [Ata](https://github.com/training-center/javascript-study-group/blob/master/material/minutes/README.md#1º-reunião) da nossa primeira reunião, obrigado a todos!!

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?
