### ISSUE TITLE
Blog do grupo de estudos javascript

### ISSUE THREAD

**Issue by landercosta** [training-center/javascript-study-group#3]
Na reunião que tivemos hoje (13/01/18), decidimos montar um blog usando a plataforma medium para registrar o andamento do grupo, repassar o conhecimento que aprendermos etc.

Uma das ideias que tivemos, foi a de registrar aqui, opiniões de quais assuntos poderíamos escrever seguindo esses passos:
1. Os participantes registram aqui uma ideia de artigo. Ex: "Uso do discord como plataforma de estudos em grupo".
2. Um participante que quiser escrever um artigo, olha a lista de assuntos sugeridos, escolhe o tema, escreve o artigo e envia para que os outros participantes do grupo façam uma revisão antes do artigo ser publicado.
3. Após as revisões, o artigo segue para o medium.

Sugestões de assuntos podem facilitar aqueles casos em que pessoas tem boas ideias, mas não querem (ou não se sentem a vontade) escrever e também quando uma pessoa quer escrever, mas ainda não sabe exatamente sobre o que. Mas se aparecer uma ideia boa que não estiver aqui, está livre para enviar o texto pra ser publicado mesmo assim.

Qualquer sugestão é bem-vinda para podermos melhorar esse processo.

**Comment by AlexsandroSA** [comment]
Boa @landercosta, isso ai. Podemos fazer algo parecido com o [post-mais](https://github.com/frontendbr/poste-mais) do [frontendbr](https://github.com/frontendbr) o que acha?

**Comment by adrianoavelino** [comment]
Achei legal a criação do Blog, porém não estaríamos descentralizando o conteúdo do Training Center que já possui um Blog no Medium e que também casaria com o interesse de gerar mais conteúdo para o mesmo?

**Comment by AlexsandroSA** [comment]
@adrianoavelino em parte sim mas como nosso blog é algo voltado, mais uma ferramenta ou metodologia de ensino que definimos, com posts predominantemente sobre JavaScript e experiências do participantes por isso pensamos em criar algo apartado.

Confesso que gostaria muito que as pessoas do grupo escrevessem para o blog oficial.

Vou pergunta se tem algum problema em criar um blog separado. @woliveiras ou @lbighetti podem me responder isso, tem algum problema?  :smile:

**Comment by woliveiras** [comment]
Fala, pessoal!

Na minha opinião, não tem problema criar um blog separado. Porém seria muito mais construtivo pra nossa comunidade se o conteúdo de vocês fosse postado direto na nossa publicação no Medium, pois alcançaria as pessoas que já nos seguem.

Mostraria pras pessoas que os grupos de estudos estão dando frutos e isso seria extremamente recompensador pra galera que está fazendo o Training Center dar certo (não nós da organização, quem compartilha o Training Center nas redes sociais também quer ver o sucesso das nossas iniciativas).

Se vocês criarem uma publicação do zero, terão que buscar as pessoas de novo, formar uma comunidade em volta do conteúdo de vocês. Igual fizemos com o conteúdo do Training Center.

Hoje temos uma média de quase 40 mil acessos por mês em nossos posts, por exemplo. Colocando os textos de vocês ali seria um apoio imenso ao nosso público.

Claro que divulgaríamos o conteúdo de vocês, mas o próprio Medium já faz isso pra gente quando subimos artigos lá. Da menos trabalho e fica mais fácil de nos organizarmos também. :) 

Eu, pessoalmente, vou ficar muito feliz se vocês escreverem artigos. Seja no Training Center ou fora, pois o importante pra gente é vocês compartilharem seu conhecimento. Mas se subirem no TC eu fico mais feliz ainda! :joy:

**Comment by lflimeira** [comment]
Minha opinião de forma rápida, pensando em open source, seria muito mais construtivo colaborar com algo que já existe do que fazer algo novo que vai demorar um tempo para se consolidar, o TC já tem uma quantidade grande de  seguidores, isso daria mais visualização para a galera que produz os artigos tbm 😆

**Comment by landercosta** [comment]
Faz mais sentido publicar no blog do training center.
Obrigado pela opinião de vocês.

**Comment by AlexsandroSA** [comment]
Grato pelo feedback. Vou levantar essas questões na próxima reunião e descobrir o que o pessoal pensa a respeito disso.

Eu particulamente não vejo problema algum até pretendo escrever pra o CT em breve.
