### ISSUE TITLE
Sugestão de Projeto  - Calculadora TDD

### ISSUE THREAD

**Issue by david81brs** [training-center/javascript-study-group#4]
Segue o repositório com a sugestão de projeto inicial em javascript com Test Driven Development - ref. Reunião de 20/01/2018.
[calc-tdd](https://github.com/david81brs/calc-tdd.git).

**Comment by AlexsandroSA** [comment]
Boa, man.

Vou levar essa sugestão para o grupo! :)

**Comment by WendellAdriel** [comment]
Não estou a participar das reuniões nem nada, mas como participo do TC há algum tempo estou a dar uma olhada no grupo de estudos e achei interessante a sugestão desse projeto como primeiro projeto, principalmente abordando o TDD, queria apenas dar algumas sugestões, que vocês que estão participando podem validar se é algo que vale a pena fazer:

- Utilizar a sintaxe de módulos do **ES6**
- Utilizar **ESLint**
- Programar com nomes de funções, métodos, arquivos, etc em inglês

**Comment by annielmenezes** [comment]
@WendellAdriel penso assim: a utilização da sugestões devem ser implementadas no decorrer do estudo, na última reunião o pessoal ficou um pouco confuso com a questão de modulos e configurações de testes e utilização de sintaxe (dúvidas entre ES5 / ES6)

**Comment by WendellAdriel** [comment]
@annielmenezes entendo perfeitamente, como eu disse eram apenas sugestões, pois como não estou a participar não sei como está a situação do grupo!!! :wink:

**Comment by AlexsandroSA** [comment]
@WendellAdriel obrigado pelas dicas!!

@annielmenezes na ultima reunião acabamos saindo um pouco da nossa pauta e tentando coisas comoTDD algo que nem todos dominam ainda - \o - é natural e acho super importante essas confusões.

Compartilhei com o grupo e agradeço seus comentários!
