### ISSUE TITLE
Blog: Próximo passo! 

### ISSUE THREAD

**Issue by AlexsandroSA** [training-center/javascript-study-group#5]
Na tentativa de incentivar a troca de conhecimentos ficou acordado a utilização de um blog¹  como uma das ferramentas de aprendizado. 

A pesquisa a baixo é destinada a isso: 

[https://goo.gl/forms/jQCGCQyGLH88X8ED2](https://goo.gl/forms/jQCGCQyGLH88X8ED2)

O objetivo dessa pesquisa é coletar informações sobre nosso primeiro post e futuras postagens.

__Informações uteis:__
 - A pesquisa inicia hoje e termina dia 01/02 _(quinta-feira)_ as 22:00 horário de Brasília. 
 - O resultado da pesquisa vai ser postado no grupo e aqui junto com a pre-pauta.

Sinta-se a vontade para sugerir melhorias!  

---
1. _Para mais detalhes veja a [issue](https://github.com/training-center/javascript-study-group/issues/3)_

**Comment by woliveiras** [comment]
Boa, mano!
