### ISSUE TITLE
Projeto: Calculadora

### ISSUE THREAD

**Issue by AlexsandroSA** [training-center/javascript-study-group#6]
Seguindo a sugestão do @david81brs na [issue](https://github.com/training-center/javascript-study-group/issues/4) vamos as definições do nosso primeiro projeto.

A baixo segue algumas sugestõe para facilitar o entendimento do projeto (sinta-se  a vontate para discordar ou sugerir novas features).

##  "Calculadora Simples"

O objetivo desse projeto é criar uma calculadora em nodejs que efetue as seguintes operações:
 - Soma
 - Subtração
 - Multiplicação
 - Divisão

#### Informações uteis:

__Req. 1:__ Cada operação receber 2 parâmetros
__Req. 2:__ Os parâmetros são sempre numeros
__Req. 3:__ Apos processar o operação a mesma deve exibir o resultado para o usuário
__Req. 4:__ Qualquer variação de parâmetros ou tipos deve ser tratada como erro e reportada a usuário 

### Requisitos obrigatórios:
 - Executar as operações listadas anteriormente (Soma, Subtração, Multiplicação e Divisão) 
 - Testar para todas as operações listadas anteriormente (Soma, Subtração, Multiplicação e Divisão) 
 - Documentação: Como execultar o programa e os respectivos testes

### Requisitos desejados:
 - Code style

### Definição de pronto:

A calculadora deve executar todas as operações informadas anteriormente assim como os respectivos testes além de incluir uma documentação de como executar e operar a mesma.

#### Checklist do projeto:
- [ ] Soma
- [ ] Documentação
- [ ] Subtração 
- [ ] Multiplicação
- [ ] Divisão
- [ ] Testes

## A definir

- Data de inicio e termino do projeto?
- Desenvolvimento em grupo ou individual?

**Comment by isaacguerreir** [comment]
Eu acho que podiamos começar o projeto nessa sexta-feira(9) e finalizar no próximo sabado(17).

Acho que o desenvolvimento deveria ser individual, mas uma issue deveria ser aberta aqui no github para caso alguém tenha problemas.
