### ISSUE TITLE
Blog: Resultado da pesquia

### ISSUE THREAD

**Issue by AlexsandroSA** [training-center/javascript-study-group#8]
Segue o resultado da pesquisa com inicio no dia **01/02** até hoje dia **06/02**. 

Para mais informações, veja [issue](https://github.com/training-center/javascript-study-group/issues/5).

![escrever-no-blog-do-ct](https://user-images.githubusercontent.com/1703378/35919882-708e2e58-0bfd-11e8-830e-3cceb0323214.png)
_Gostaria de escrever para o blog do Training Center?_

---
Grato a todos,
E em breve nosso primeiro post! :)

**Comment by Diego-Brocanelli** [comment]
Olá, @AlexsandroSA .

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?
