### ISSUE TITLE
Projeto: Calculadora, e lá vamos nós!! 

### ISSUE THREAD

**Issue by AlexsandroSA** [training-center/javascript-study-group#9]
Fala pessoal,

Vamos iniciar o nosso primeiro projeto, a nossa __"Calculadora Simples"__, [veja aqui mais informações sobre o projeto](https://github.com/training-center/javascript-study-group/issues/6)

---
### Dúvidas

| _"Não existe pergunta besta"_ 

| _"Sua dúvida pode ser a dúvida de outra pessoa"_ 

Então pergunte, questione, sinta-se a vontade essas issue está aqui pra isso. 

Dicas e sugestões são sempre bem-vindas!! 

---
### Terminou o projeto

Compartilhe conosco. Ao finalizar o projeto envie no comentário o link do seu repositorio (lembre de cumprir todas as exigências)

---
### Boa sorte a todos, bons estudos e "que os jogos comecem"

**Comment by Morette** [comment]
E aí pessoal, como anda o projeto de vocês?

**Comment by AlexsandroSA** [comment]
Já fiz boa parte, em breve publico o link do projeto aqui, acabei me mudando e estou sem internet temporariamente.  

Mas se tiver alguma dúvida ou sugestão estamos as ordens! :)
E você  @Morette  já fez alguma coisa?

**Comment by Morette** [comment]
@AlexsandroSA já sim, estou tentando fazer a calculadora utilizando html e css também
estou meio parado porque estou tentando terminar o JS Ninja e com o trabalho fico um pouco sem tempo...
:(

**Comment by AlexsandroSA** [comment]
https://github.com/AlexsandroSA/studies/tree/master/js-com-tdd-na-pratica/calculadora-simples

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by AlexsandroSA** [comment]
Opa, obrigado @Diego-Brocanelli, vou fechar!!
